

name: srinivas-project 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: tomcat deploy 
      run: curl -v -u admin:Admin -T /home/runner/work/srinivas-project/srinivas-project/target/myweb-8.2.0.war 'http://ec2-15-207-100-180.ap-south-1.compute.amazonaws.com:8080//manager/text/deploy?path=/springaction'

   
